spring:
    application:
        name: cryptography
    docker:
        compose:
            lifecycle-management: none
    jpa:
        open-in-view: false
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
        contexts: base
        enabled: true
    profiles:
        active: ${APP_PROFILE:dev} 

crypt:
    secret:
        password: ${CRYPT_PASSWORD:mypassword}
        salt: ${CRYPT_PASSWORD:mysalt}
